name: tripy_ev_stable
description: "A new Flutter project."

publish_to: "none"

version: 1.0.8+9
scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  model_build: "dart run build_runner build --delete-conflicting-outputs"
  assets_gen: "dart run assets_gen build"
  activate_rps: "dart pub global activate rps --version 0.7.0-dev.6"

  fc: "flutter clean"
  fpg: "flutter pub get"
environment:
   sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  firebase_core: ^2.24.2
  wakelock_plus: ^1.1.4
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.1.0
  sentry_flutter: ^7.15.0
  stacked: ^3.4.2
  google_fonts: ^5.1.0
  bottom_sheet: ^4.0.4
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.0.0
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_svg: ^2.0.9
  collection: ^1.17.1
  connectivity_plus: ^5.0.2
  dio: ^5.3.1
  logger: ^1.1.0
  retry: ^3.1.0
  sembast: ^3.3.1+1
  sembast_web: ^2.0.1+1
  intl: ^0.19.0
  theme_extensions_builder_annotation: ^2.0.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  ionicons: ^0.2.2
  another_flushbar: ^1.12.30
  device_info: ^2.0.3
  platform_device_id_platform_interface: ^1.0.0
  mask_text_input_formatter: ^2.9.0
  flutter_widget_from_html: ^0.14.11
  animate_do: ^3.3.4
  sms_autofill: ^2.3.1
  pinput: ^4.0.0
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_holo_date_picker: ^1.1.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  animated_toggle_switch: ^0.8.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner:
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.0
  build_runner: 2.3.3
  hive_generator: ^2.0.1
  theme_extensions_builder: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/audios/
    - assets/images/
    - assets/lotties/
    - assets/introduce/
    - assets/svgs/
    - assets/pdfs/
    - assets/jsons/
    - assets/flags/
    - assets/languages/
    - assets/svgs/home/
    - assets/svgs/map/

